on:
    push:
        branches:
            - main

name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js 20.0.0
      uses: actions/setup-node@v2
      with:
        node-version: '20.0.0'
      
    - name: ðŸ”¨ Build Project
      run: |
        npm install
        npm install -g pm2
        pm2 -v
        npm run build

    - name: ðŸ“‚ List Local Files
      run: |
        ls -R ./build
        
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: ./build
        remote_dir: /build

    - name: ðŸš€ Start Strapi
      run: |
        pm2 stop strapi || true
        pm2 start ecosystem.config.js
